### ISSUE TITLE
Typo in `sensetive` configuration in `.rultor.yml`

### ISSUE THREAD

**Issue by IlyaLisov** [eo-cqrs/eo-kafka#486]
I found field that is not documented by Rultor docs, also it has a typo in word `sensetive` in `.rultor.yml`

```
release:
  pre: false
  sensetive:
    - settings.xml
```
